INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Project Update', '+905325323231', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - New Task Assigned', '+905325323233', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Deadline Reminder', '+905325323234', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Meeting Schedule', '+905325323235', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Project Update - Phase 1', '+905325323236', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Action Required', '+905325323237', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Final Reminder', '+905325323238', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Urgent: Task Due', '+905325323239', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Task Completed', '+905325323240', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Upcoming Event', '+905325323241', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - New Notification', '+905325323242', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Task Update', '+905325323243', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Follow-up Required', '+905325323244', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Task Deadline Extended', '+905325323245', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Urgent Meeting', '+905325323246', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Project Review', '+905325323247', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Reminder: Project Task', '+905325323248', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Upcoming Deadline', '+905325323249', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Urgent Action Needed', '+905325323250', 'NOT_SENT');
INSERT INTO `insider`.`message` (`message_content`, `phone_number`, `status`) VALUES ('Insider - Task Overdue', '+905325323251', 'NOT_SENT');
